# Generated by Django 4.0.4 on 2022-06-28 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id_alumno', models.AutoField(primary_key=True, serialize=False)),
                ('nombres_alumno', models.CharField(max_length=100)),
                ('apellidos_alumno', models.CharField(max_length=100)),
                ('edad', models.FloatField()),
            ],
            options={
                'db_table': 'alumno',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Alumnopie',
            fields=[
                ('id_alumnopie', models.AutoField(primary_key=True, serialize=False)),
                ('justificativo_ingreso', models.CharField(max_length=500)),
                ('fecha_ingreso', models.DateField()),
            ],
            options={
                'db_table': 'alumnopie',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Apoderado',
            fields=[
                ('id_apoderado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_apoderado', models.CharField(max_length=50)),
                ('apellido_apoderado', models.CharField(max_length=50)),
                ('celular', models.IntegerField()),
                ('correo', models.EmailField(max_length=50)),
            ],
            options={
                'db_table': 'apoderado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id_comuna', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_comuna', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'comuna',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cupoextra',
            fields=[
                ('id_cupoextra', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_solicitud', models.DateField()),
                ('justificacion_cupo', models.CharField(max_length=200)),
                ('documento', models.ImageField(null=True, upload_to='DOCUMENTO')),
            ],
            options={
                'db_table': 'cupoextra',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id_curso', models.AutoField(primary_key=True, serialize=False)),
                ('nomcurso', models.CharField(max_length=20)),
                ('cupos', models.IntegerField()),
                ('cupos_pie', models.IntegerField()),
            ],
            options={
                'db_table': 'curso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Escuela',
            fields=[
                ('id_escuela', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_escuela', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=1000)),
                ('imagen', models.ImageField(null=True, upload_to='logo')),
            ],
            options={
                'db_table': 'escuela',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id_diagnostico', models.AutoField(primary_key=True, serialize=False)),
                ('archivos_diagnostico', models.ImageField(null=True, upload_to='EVALUACION')),
                ('evaluacion_especialista', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'evaluacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id_muni', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_muni', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'municipio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pfs',
            fields=[
                ('id_pfs', models.AutoField(primary_key=True, serialize=False)),
                ('psicopedagogia', models.BooleanField()),
                ('terapeutaocupacional', models.BooleanField()),
                ('pediatra', models.BooleanField()),
                ('fonoaudiologa', models.BooleanField()),
                ('ed_diferencial', models.BooleanField()),
            ],
            options={
                'db_table': 'pfs',
                'managed': False,
            },
        ),
    ]
