from lib2to3.pgen2.token import NAME
from pathlib import Path
from unicodedata import name
from django.urls import path
from .views import *
urlpatterns = [
    path('',home, name="home" ),
    path('listarEstablecimiento/', listarEstablecimiento , name="listarEstablecimiento"),
    path('listarAlumno/', listarAlumno, name="listarAlumno"),
    path('formularioescuela/', formularioescuela , name="formularioescuela" ),
    path('formularioalumno/',formularioalumno, name="formularioalumno"),
    path('formularioapoderado/',formularioapoderado, name="formularioapoderado"),
    path('formularioalumnopie/', formularioalumnopie, name="formularioalumnopie"),
    path('formularioespecialista/',formularioespecialista, name="formularioespecialista"),
    path('agregarcomuna/', agregarcomuna, name="agregarcomuna"),
    path('agregarmuni/', agregarmuni, name="agregarmuni"),
    path('agregarcurso/', agregarcurso, name="agregarcurso"),
    path('agregarcupo/', agregarcupo, name="agregarcupo"),
    path('agregarevaluacion/',agregarevaluacion, name="agregarevaluacion" ),
    path('listarespecialista/', listarespecialista , name="listarespecialista"),
    path('listaralumnopie/',listaralumnopie, name="listaralumnopie"),
    path('listarcurso/', listarcurso, name="listarcurso"),
    path('listarapoderado/', listarapoderado, name="listarapoderado"),
    path('listarevaluacion/', listarevaluacion, name="listarevaluacion"),
    path('modificar_Alumno/<id_alumno>', modificar_Alumno, name="modificar_Alumno"),
    path('eliminar_Alumno/<id_alumno>', eliminar_Alumno, name="eliminar_Alumno"),
    path('modificar_AlumnoPie/<id_alumnopie>', modificar_AlumnoPie, name="modificar_AlumnoPie"),
    path('eliminar_AlumnoPie/<id_alumnopie>', eliminar_AlumnoPie, name="eliminar_AlumnoPie"),
    path('modificar_Apoderado/<id_apoderado>', modificar_Apoderado, name="modificar_Apoderado"),
    path('eliminar_Apoderado/<id_apoderado>', eliminar_Apoderado, name="eliminar_Apoderado"),
    path('modificar_Curso/<id_curso>', modificar_Curso, name="modificar_Curso"),
    path('eliminar_Curso/<id_curso>', eliminar_Curso , name="eliminar_Curso"),
    path('modificar_Pfs/<id_pfs>', modificar_Pfs, name="modificar_Pfs"),
    path('eliminar_Pfs/<id_pfs>', eliminar_Pfs, name="eliminar_Pfs"), 
    path('modificar_Establecimiento/<id_escuela>', modificar_Establecimiento , name="modificar_Establecimiento"),
    path('eliminar_Establecimiento/<id_escuela>', eliminar_Establecimiento, name="eliminar_Establecimiento"),
    path('modificar_Evaluacion/<id_diagnostico>', modificar_Evaluacion, name="modificar_Evaluacion"),
    path('eliminar_Evaluacion/<id_diagnostico>', eliminar_Evaluacion, name="eliminar_Evaluacion"),
    path('registro/', registro, name="registro"),
    path('listarcomuna/', listarcomuna , name="listarcomuna"),
    path('modificar_Comuna/<id_comuna>', modificar_Comuna , name="modificar_Comuna"),
    path('eliminar_Comuna/<id_comuna>', eliminar_Comuna , name="eliminar_Comuna"),
    path('listarmuni/', listarmuni , name="listarmuni"),
    path('modificar_Muni/<id_muni>', modificar_Muni , name="modificar_Muni"),
    path('eliminar_Muni/<id_muni>', eliminar_Muni , name="eliminar_Muni"),
    path('modificar_cupo/<id_cupoextra>', modificar_cupo , name="modificar_cupo"),
    path('eliminar_Cupo/<id_cupoextra>', eliminar_Cupo , name="eliminar_Cupo"),
    path('listarcupo/', listarcupo , name="listarcupo"),

]
